databases:
  - name: mapsurvey-db
    plan: basic-256mb
    databaseName: mapsurvey
    user: mapsurvey
    postgresMajorVersion: 16
    ipAllowList: []

services:
  - type: web
    name: mapsurvey
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mapsurvey-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        value: "localhost mapsurvey.org mapsurvey.render.com"
      - key: MAPBOX_ACCESS_TOKEN
        sync: false
    disk:
      name: media-storage
      mountPath: /home/app/web/mediafiles
      sizeGB: 1
    healthCheckPath: /
